### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by dreadnip** [BrkIt/BrkIt.github.io#1]
Hey man, if you'd like I could add some CSS to make your calculator easier to use (and look better!). What do you think?

**Comment by BrkIt** [comment]
Yeah sure! I'd love that. CSS is my worst nightmare!

**Comment by dreadnip** [comment]
Did a couple of things, feel free to leave feedback on the PRs.

**Comment by BrkIt** [comment]
I like most of what you've done!

I think the spacing between each line is too much though.

With the new design, a scroll bar for the output might look good for low level skills.

**Comment by dreadnip** [comment]
You can play with the CSS. The margin between the rows can be found in .form-row. I probably used a .form-row + .form-row selector.
